# Generated by Django 5.2.4 on 2025-07-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulas', '0002_formula_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
