# Generated by Django 5.2.4 on 2025-07-25 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulas', '0003_alter_formula_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formula',
            name='component',
        ),
        migrations.RemoveField(
            model_name='formula',
            name='formula_key',
        ),
        migrations.CreateModel(
            name='CalculationTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('formula_key', models.CharField(max_length=255)),
                ('component', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(choices=[('economy', 'Economy'), ('hr', 'HR')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
