# Generated by Django 5.2.4 on 2025-08-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulas', '0004_remove_formula_component_remove_formula_formula_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationtool',
            name='formula_info',
            field=models.TextField(blank=True),
        ),
    ]
