# Generated by Django 5.2.4 on 2025-08-27 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulas', '0005_calculationtool_formula_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculationtool',
            name='category',
        ),
        migrations.RemoveField(
            model_name='formula',
            name='category',
        ),
        migrations.RemoveField(
            model_name='template',
            name='category',
        ),
    ]
