# Generated by Django 5.2.4 on 2025-08-27 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulas', '0006_remove_calculationtool_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationToolCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='calculationtool',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='formulas.calculationtoolcategory'),
        ),
    ]
