# Generated by Django 5.2.4 on 2025-08-27 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulas', '0007_calculationtoolcategory_calculationtool_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calculationtoolcategory',
            options={'verbose_name_plural': 'calculation tool categories'},
        ),
        migrations.AlterField(
            model_name='calculationtool',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formulas.calculationtoolcategory'),
        ),
    ]
