# Generated by Django 5.2.4 on 2025-08-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulas', '0009_conversiontool'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
