# Generated by Django 5.2.4 on 2025-10-09 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulas', '0010_term'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculationtool',
            name='formula_key',
        ),
    ]
