# Generated by Django 5.2.4 on 2025-12-09 16:38

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulas', '0011_remove_calculationtool_formula_key'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
