# Generated by Django 5.2.4 on 2025-10-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, default='defaults/default.png', null=True, upload_to='profile_photos/'),
        ),
    ]
